data:
    aec:
        load:
            options:
            - "antiXray:"
            - "    status: false"
            - " "
            - "register:"
            - "    status: false"
            - "    time: 10"
            - "decoCombat:"
            - "    status: false"
            - "    time: 30"